version: '3'

services:
  configserver:
    image: edthrasht/configserver:1

  studentservice:
    image: edthrasht/studentservice:1
    depends_on: 
      - configserver
      - mysql-db-school
    ports: 
      - 8081:8081
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker

  professorservice:
    image: edthrasht/professorservice:1
    depends_on: 
      - configserver
      - mysql-db-school
    ports: 
      - 8082:8082
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker

  signatureservice:
    image: edthrasht/signatureservice:1
    depends_on: 
      - configserver
      - mysql-db-school
    ports: 
      - 8084:8084
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker

  mysql-db-school:
    build: ./school_database
    volumes:
      - school-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql

volumes:
  school-data:
