version: '3'

services:
  configserver:
    image: edthrasht/configserver:1

  studentservice:
    image: edthrasht/studentservice:1
    depends_on: 
      - configserver
      - mysql-db-students
    ports: 
      - 8081:8081
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker

  professorservice:
    image: edthrasht/professorservice:1
    depends_on: 
      - configserver
      - mysql-db-professors
    ports: 
      - 8082:8082
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker

  signatureservice:
    image: edthrasht/signatureservice:1
    depends_on: 
      - configserver
      - mysql-db-signatures
    ports: 
      - 8084:8084
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker

  mysql-db-students:
    image: mysql
    volumes:
      - students-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: students

  mysql-db-professors:
    image: mysql
    volumes:
      - professors-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: professors

  mysql-db-signatures:
    image: mysql
    volumes:
      - signatures-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: signatures

volumes:
  students-data:
  professors-data:
  signatures-data: